version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dnd_combat
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_TYPE: postgres
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/dnd_combat?sslmode=disable
      JWT_SECRET: development-secret-change-in-production
      PORT: 5000
      ENV: development
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: 